install.packages("tm")
install.packages("SnowballC")
install.packages("wordcloud")
install.packages("RColorBrewer")
install.packages("stringr")
library("tm")
library("SnowballC")
library("RColorBrewer")
library("stringr")
library("wordcloud2")
library("plyr")

label <- read_excel("D:/Data_Crawling_Instagram.xlsx")
Label <-label $Text
positif<-scan("D:/s-pos.txt",what="character",comment.char=";") 
negatif<-scan("D:/s-neg.txt",what="character",comment.char=";") 
kata.positif = c(positif, "senang") 
kata.negatif = c(negatif, "kecewa")
score.sentiment = function(Label, kata.positif, kata.negatif, .progress='none')
{  
  require(plyr)
  require(stringr) 
  scores = laply(Label, function(kalimat, kata.positif, kata.negatif)
  {  
    kalimat = gsub('[[:punct:]]', '', kalimat)  
    kalimat = gsub('[[:cntrl:]]', '', kalimat)  
    kalimat = gsub('\\d+', '', kalimat)  
    kalimat = tolower(kalimat)
    list.kata = str_split(kalimat, '\\s+')
    kata2 = unlist(list.kata) 
    positif.matches = match(kata2, kata.positif)  
    negatif.matches = match(kata2, kata.negatif)  
    positif.matches = !is.na(positif.matches)  
    negatif.matches = !is.na(negatif.matches)
    score = sum(positif.matches) -(sum(negatif.matches))  
    return(score)
  },kata.positif, kata.negatif, .progress=.progress )
  scores.df = data.frame(score=scores, text=Label)  
  return(scores.df)
}
hasil = score.sentiment(Label, kata.positif, kata.negatif)
hasil$klasifikasi<-ifelse(hasil$score<0, "Negatif","Positif")
data <-hasil[c(3,1,2)]
View(hasil)
data<-hasil[c(3,1,2)] 
View(data) 
write.csv(data,"D:/hasil_pelabelan.csv") 